-- File generated by the BNF Converter (bnfc 2.9.4.1).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Language.Templatespiler.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Language.Templatespiler.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Language.Templatespiler.Abs.Ident -> Result
transIdent x = case x of
  Language.Templatespiler.Abs.Ident string -> failure x

transType :: Show a => Language.Templatespiler.Abs.Type' a -> Result
transType x = case x of
  Language.Templatespiler.Abs.IntegerType _ -> failure x
  Language.Templatespiler.Abs.StringType _ -> failure x
  Language.Templatespiler.Abs.FloatType _ -> failure x
  Language.Templatespiler.Abs.CombinatorType _ combinator -> failure x

transTerminalBinding :: Show a => Language.Templatespiler.Abs.TerminalBinding' a -> Result
transTerminalBinding x = case x of
  Language.Templatespiler.Abs.SingleBinding _ ident type_ -> failure x
  Language.Templatespiler.Abs.ParenBinding _ terminalbinding -> failure x

transBindingGroup :: Show a => Language.Templatespiler.Abs.BindingGroup' a -> Result
transBindingGroup x = case x of
  Language.Templatespiler.Abs.BindingGroup _ terminalbindings -> failure x

transBindingOrCombinator :: Show a => Language.Templatespiler.Abs.BindingOrCombinator' a -> Result
transBindingOrCombinator x = case x of
  Language.Templatespiler.Abs.NamedBinding _ terminalbinding -> failure x
  Language.Templatespiler.Abs.UnnamedBinding _ combinator -> failure x

transCombinator :: Show a => Language.Templatespiler.Abs.Combinator' a -> Result
transCombinator x = case x of
  Language.Templatespiler.Abs.ParenCombinator _ combinator -> failure x
  Language.Templatespiler.Abs.ArrayCombinator _ varorconstint bindingorcombinator -> failure x
  Language.Templatespiler.Abs.SepByCombinator _ string bindinggroup -> failure x
  Language.Templatespiler.Abs.ListCombinator _ bindingorcombinator -> failure x

transVarOrConstInt :: Show a => Language.Templatespiler.Abs.VarOrConstInt' a -> Result
transVarOrConstInt x = case x of
  Language.Templatespiler.Abs.ConstInt _ integer -> failure x
  Language.Templatespiler.Abs.ConstVar _ ident -> failure x

transBindingList :: Show a => Language.Templatespiler.Abs.BindingList' a -> Result
transBindingList x = case x of
  Language.Templatespiler.Abs.BindingList _ bindinglistentrys -> failure x

transBindingListEntry :: Show a => Language.Templatespiler.Abs.BindingListEntry' a -> Result
transBindingListEntry x = case x of
  Language.Templatespiler.Abs.BindingListEntry _ terminalbinding -> failure x
